export const OPERATORS = [
  { label: 'AC', type: 'function', bg: 'bg-red-500' },
  { label: 'C', type: 'function', bg: 'bg-red-500' },
  { label: '%', type: 'function', bg: 'bg-gray-700' },
  { label: '/', type: 'operator', bg: 'bg-orange-700' },
  { label: '7', type: 'number'},
  { label: '8', type: 'number'},
  { label: '9', type: 'number'},
  { label: '*', type: 'operator', bg: 'bg-orange-700' },
  { label: '4', type: 'number'},
  { label: '5', type: 'number'},
  { label: '6', type: 'number' },
  { label: '-', type: 'operator', bg: 'bg-orange-700' },
  { label: '1', type: 'number'},
  { label: '2', type: 'number'},
  { label: '3', type: 'number' },
  { label: '+', type: 'operator', bg: 'bg-orange-700' },
  { label: '0', type: 'number', bg: 'bg-gray-900 col-span-2' },
  { label: '.', type: 'number', bg: 'bg-gray-600' },
  { label: '=', type: 'operator', bg: 'bg-violet-900' },
];
