export const OPERATORS = [
  { label: 'AC', type: 'function', bg: 'bg-red-100 text-red-500' },
  { label: '+/-', type: 'function', bg: 'bg-gray-200' },
  { label: '%', type: 'function', bg: 'bg-gray-200' },
  { label: '÷', type: 'operator', bg: 'bg-orange-500 text-white' },
  { label: 7, type: 'number'},
  { label: 8, type: 'number'},
  { label: 9, type: 'number'},
  { label: '*', type: 'operator', bg: 'bg-orange-500 text-white' },
  { label: 4, type: 'number'},
  { label: 5, type: 'number'},
  { label: 6, type: 'number' },
  { label: '-', type: 'operator', bg: 'bg-orange-500 text-white' },
  { label: 1, type: 'number'},
  { label: 2, type: 'number'},
  { label: 3, type: 'number' },
  { label: '+', type: 'operator', bg: 'bg-orange-500 text-white' },
  { label: 0, type: 'number', bg: 'bg-gray-200 col-span-2' },
  { label: '.', type: 'number', bg: 'bg-gray-300' },
  { label: '=', type: 'operator', bg: 'bg-orange-600 text-white' },
];
