interface ButtonsConfig {
  label: string;
  value: string;
  type: string;
  bg?: string;
}

export const MAIN_BUTTONS: ButtonsConfig[] = [
  { label: 'AC', value: 'AC', type: 'function', bg: 'bg-red-500' },
  { label: 'C', value: 'C', type: 'function', bg: 'bg-red-500' },
  { label: '␣', value: ' ', type: 'function', bg: 'bg-red-500' },
  { label: '⌫', value: 'DEL', type: 'function', bg: 'bg-red-500' },
  { label: '÷', value: '/', type: 'operator', bg: 'bg-orange-700' },
  { label: '7', value: '7', type: 'number', bg: 'bg-black' },
  { label: '8', value: '8', type: 'number', bg: 'bg-black' },
  { label: '9', value: '9', type: 'number', bg: 'bg-black' },
  { label: '×', value: '*', type: 'operator', bg: 'bg-orange-700' },
  { label: '4', value: '4', type: 'number', bg: 'bg-black' },
  { label: '5', value: '5', type: 'number', bg: 'bg-black' },
  { label: '6', value: '6', type: 'number', bg: 'bg-black' },
  { label: '-', value: '-', type: 'operator', bg: 'bg-orange-700' },
  { label: '1', value: '1', type: 'number', bg: 'bg-black' },
  { label: '2', value: '2', type: 'number', bg: 'bg-black' },
  { label: '3', value: '3', type: 'number', bg: 'bg-black' },
  { label: '+', value: '+', type: 'operator', bg: 'bg-orange-700' },
  { label: '.', value: '.', type: 'number', bg: 'bg-gray-600' },
  { label: '0', value: '0', type: 'number', bg: 'bg-gray-900' },
  { label: '=', value: '=', type: 'operator', bg: 'bg-violet-900' },
];

export const SCI_BUTTONS: ButtonsConfig[] = [
  {
    label: 'sin',
    value: 'sin(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'cos',
    value: 'cos(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'tan',
    value: 'tan(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'cot',
    value: 'cot(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'log',
    value: 'log(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'log2',
    value: 'log2(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'log10',
    value: 'log10(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: 'sum',
    value: 'sum(',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: '^',
    value: '^',
    type: 'operator',
    bg: 'bg-red-200',
  },
  {
    label: 'x!',
    value: '!',
    type: 'function',
    bg: 'bg-red-200',
  },
  {
    label: '√',
    value: 'sqrt(',
    type: 'function',
    bg: 'bg-yellow-200',
  },
  {
    label: 'ⁿ√y',
    value: 'nthRoot(',
    type: 'function',
    bg: 'bg-yellow-200',
  },
  {
    label: '∛x',
    value: 'cbrt(',
    type: 'function',
    bg: 'bg-yellow-200',
  },
  { label: 'π', value: 'pi', type: 'number', bg: 'bg-yellow-200' },
  { label: 'e', value: 'e', type: 'number', bg: 'bg-yellow-200' },
  { label: 'prime', value: 'isPrime(', type: 'function', bg: 'bg-yellow-200' },
  { label: 'med', value: 'median(', type: 'function', bg: 'bg-yellow-200' },
  {
    label: 'bell',
    value: 'bellNumbers(',
    type: 'theory',
    bg: 'bg-yellow-200',
  },
  {
    label: 'lgam',
    value: 'lgamma(',
    type: 'function',
    bg: 'bg-yellow-200',
  },
  {
    label: 'comp',
    value: 'composition(',
    type: 'function',
    bg: 'bg-yellow-200',
  },
  {
    label: 'A ∪ B',
    value: 'setUnion([',
    type: 'set',
    bg: 'bg-sky-300',
  },
  {
    label: 'A ∩ B',
    value: 'setIntersect([',
    type: 'set',
    bg: 'bg-sky-300',
  },
  {
    label: 'P(A)',
    value: 'setPowrset([',
    type: 'set',
    bg: 'bg-sky-300',
  },
  {
    label: 'A ⊗ B',
    value: 'setDifference([',
    type: 'set',
    bg: 'bg-sky-300',
  },
  { label: 'kron', value: 'kron([', type: 'matrix', bg: 'bg-sky-300' },
  { label: 'bin', value: 'bin(', type: 'function', bg: 'bg-sky-300' },
  {
    label: 'rand',
    value: 'random()',
    type: 'function',
    bg: 'bg-sky-300',
  },
  {
    label: 'n₁n₂!',
    value: 'multinomial([',
    type: 'theory',
    bg: 'bg-sky-300',
  },
  {
    label: 'hypot',
    value: 'hypot(',
    type: 'function',
    bg: 'bg-sky-300',
  },
  {
    label: 'fix',
    value: 'fix(',
    type: 'function',
    bg: 'bg-sky-300',
  },

  {
    label: 'mod',
    value: 'mod(',
    type: 'function',
    bg: 'bg-orange-200',
  },
  {
    label: 'equal',
    value: '==',
    type: 'operator',
    bg: 'bg-orange-200',
  },
  {
    label: '!equal',
    value: '!=',
    type: 'operator',
    bg: 'bg-orange-200',
  },

  {
    label: 'and',
    value: 'and',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'nand',
    value: 'nand',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'or',
    value: 'or',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'nor',
    value: 'nor',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'xor',
    value: 'xor',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'not',
    value: 'not',
    type: 'logic',
    bg: 'bg-orange-200',
  },
  {
    label: 'abs',
    value: 'abs(',
    type: 'function',
    bg: 'bg-orange-200',
  },
  {
    label: 'max',
    value: 'max(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'min',
    value: 'min(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'exp',
    value: 'exp(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'mean',
    value: 'mean(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'ceil',
    value: 'ceil(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'floor',
    value: 'floor(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'round',
    value: 'round(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'bin',
    value: 'bin(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'gcd',
    value: 'gcd(',
    type: 'function',
    bg: 'bg-secondary',
  },
  {
    label: 'lcm',
    value: 'lcm(',
    type: 'function',
    bg: 'bg-secondary',
  },

  {
    label: '%',
    value: '%',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
  { label: '<', value: '<', type: 'operator', bg: 'bg-fuchsia-200' },
  { label: '>', value: '>', type: 'operator', bg: 'bg-fuchsia-200' },
  {
    label: '<=',
    value: '<=',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
  {
    label: '>=',
    value: '>=',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
  { label: '[', value: '[', type: 'operator', bg: 'bg-fuchsia-200' },
  { label: ']', value: ']', type: 'operator', bg: 'bg-fuchsia-200' },
  {
    label: '(',
    value: '(',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
  {
    label: ')',
    value: ')',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
  {
    label: ',',
    value: ',',
    type: 'operator',
    bg: 'bg-fuchsia-200',
  },
];
